export const COUNTRY_PREFIXES = [
  { country: "Afganistán", code: "AF", prefix: "+93", flag: "🇦🇫" },
  { country: "Albania", code: "AL", prefix: "+355", flag: "🇦🇱" },
  { country: "Alemania", code: "DE", prefix: "+49", flag: "🇩🇪" },
  { country: "Andorra", code: "AD", prefix: "+376", flag: "🇦🇩" },
  { country: "Angola", code: "AO", prefix: "+244", flag: "🇦🇴" },
  { country: "Anguila", code: "AI", prefix: "+1-264", flag: "🇦🇮" },
  { country: "Antigua y Barbuda", code: "AG", prefix: "+1-268", flag: "🇦🇬" },
  { country: "Arabia Saudita", code: "SA", prefix: "+966", flag: "🇸🇦" },
  { country: "Argelia", code: "DZ", prefix: "+213", flag: "🇩🇿" },
  { country: "Argentina", code: "AR", prefix: "+54", flag: "🇦🇷" },
  { country: "Armenia", code: "AM", prefix: "+374", flag: "🇦🇲" },
  { country: "Aruba", code: "AW", prefix: "+297", flag: "🇦🇼" },
  { country: "Australia", code: "AU", prefix: "+61", flag: "🇦🇺" },
  { country: "Austria", code: "AT", prefix: "+43", flag: "🇦🇹" },
  { country: "Azerbaiyán", code: "AZ", prefix: "+994", flag: "🇦🇿" },
  { country: "Bahamas", code: "BS", prefix: "+1-242", flag: "🇧🇸" },
  { country: "Bangladés", code: "BD", prefix: "+880", flag: "🇧🇩" },
  { country: "Barbados", code: "BB", prefix: "+1-246", flag: "🇧🇧" },
  { country: "Baréin", code: "BH", prefix: "+973", flag: "🇧🇭" },
  { country: "Bélgica", code: "BE", prefix: "+32", flag: "🇧🇪" },
  { country: "Belice", code: "BZ", prefix: "+501", flag: "🇧🇿" },
  { country: "Benín", code: "BJ", prefix: "+229", flag: "🇧🇯" },
  { country: "Bermudas", code: "BM", prefix: "+1-441", flag: "🇧🇲" },
  { country: "Bielorrusia", code: "BY", prefix: "+375", flag: "🇧🇾" },
  { country: "Birmania (Myanmar)", code: "MM", prefix: "+95", flag: "🇲🇲" },
  { country: "Bolivia", code: "BO", prefix: "+591", flag: "🇧🇴" },
  { country: "Bosnia y Herzegovina", code: "BA", prefix: "+387", flag: "🇧🇦" },
  { country: "Botsuana", code: "BW", prefix: "+267", flag: "🇧🇼" },
  { country: "Brasil", code: "BR", prefix: "+55", flag: "🇧🇷" },
  { country: "Brunéi", code: "BN", prefix: "+673", flag: "🇧🇳" },
  { country: "Bulgaria", code: "BG", prefix: "+359", flag: "🇧🇬" },
  { country: "Burkina Faso", code: "BF", prefix: "+226", flag: "🇧🇫" },
  { country: "Burundi", code: "BI", prefix: "+257", flag: "🇧🇮" },
  { country: "Bután", code: "BT", prefix: "+975", flag: "🇧🇹" },
  { country: "Cabo Verde", code: "CV", prefix: "+238", flag: "🇨🇻" },
  { country: "Camboya", code: "KH", prefix: "+855", flag: "🇰🇭" },
  { country: "Camerún", code: "CM", prefix: "+237", flag: "🇨🇲" },
  { country: "Canadá", code: "CA", prefix: "+1", flag: "🇨🇦" },
  { country: "Catar", code: "QA", prefix: "+974", flag: "🇶🇦" },
  { country: "Chad", code: "TD", prefix: "+235", flag: "🇹🇩" },
  { country: "Chile", code: "CL", prefix: "+56", flag: "🇨🇱" },
  { country: "China", code: "CN", prefix: "+86", flag: "🇨🇳" },
  { country: "Chipre", code: "CY", prefix: "+357", flag: "🇨🇾" },
  { country: "Colombia", code: "CO", prefix: "+57", flag: "🇨🇴" },
  { country: "Comoras", code: "KM", prefix: "+269", flag: "🇰🇲" },
  { country: "Corea del Norte", code: "KP", prefix: "+850", flag: "🇰🇵" },
  { country: "Corea del Sur", code: "KR", prefix: "+82", flag: "🇰🇷" },
  { country: "Costa de Marfil", code: "CI", prefix: "+225", flag: "🇨🇮" },
  { country: "Costa Rica", code: "CR", prefix: "+506", flag: "🇨🇷" },
  { country: "Croacia", code: "HR", prefix: "+385", flag: "🇭🇷" },
  { country: "Cuba", code: "CU", prefix: "+53", flag: "🇨🇺" },
  { country: "Curaçao", code: "CW", prefix: "+599", flag: "🇨🇼" },
  { country: "Dinamarca", code: "DK", prefix: "+45", flag: "🇩🇰" },
  { country: "Dominica", code: "DM", prefix: "+1-767", flag: "🇩🇲" },
  { country: "Ecuador", code: "EC", prefix: "+593", flag: "🇪🇨" },
  { country: "Egipto", code: "EG", prefix: "+20", flag: "🇪🇬" },
  { country: "El Salvador", code: "SV", prefix: "+503", flag: "🇸🇻" },
  { country: "Emiratos Árabes Unidos", code: "AE", prefix: "+971", flag: "🇦🇪" },
  { country: "Eritrea", code: "ER", prefix: "+291", flag: "🇪🇷" },
  { country: "Eslovaquia", code: "SK", prefix: "+421", flag: "🇸🇰" },
  { country: "Eslovenia", code: "SI", prefix: "+386", flag: "🇸🇮" },
  { country: "España", code: "ES", prefix: "+34", flag: "🇪🇸" },
  { country: "Estados Unidos", code: "US", prefix: "+1", flag: "🇺🇸" },
  { country: "Estonia", code: "EE", prefix: "+372", flag: "🇪🇪" },
  { country: "Etiopía", code: "ET", prefix: "+251", flag: "🇪🇹" },
  { country: "Filipinas", code: "PH", prefix: "+63", flag: "🇵🇭" },
  { country: "Finlandia", code: "FI", prefix: "+358", flag: "🇫🇮" },
  { country: "Fiyi", code: "FJ", prefix: "+679", flag: "🇫🇯" },
  { country: "Francia", code: "FR", prefix: "+33", flag: "🇫🇷" },
  { country: "Gabón", code: "GA", prefix: "+241", flag: "🇬🇦" },
  { country: "Gambia", code: "GM", prefix: "+220", flag: "🇬🇲" },
  { country: "Georgia", code: "GE", prefix: "+995", flag: "🇬🇪" },
  { country: "Ghana", code: "GH", prefix: "+233", flag: "🇬🇭" },
  { country: "Gibraltar", code: "GI", prefix: "+350", flag: "🇬🇮" },
  { country: "Granada", code: "GD", prefix: "+1-473", flag: "🇬🇩" },
  { country: "Grecia", code: "GR", prefix: "+30", flag: "🇬🇷" },
  { country: "Groenlandia", code: "GL", prefix: "+299", flag: "🇬🇱" },
  { country: "Guadalupe", code: "GP", prefix: "+590", flag: "🇬🇵" },
  { country: "Guam", code: "GU", prefix: "+1-671", flag: "🇬🇺" },
  { country: "Guatemala", code: "GT", prefix: "+502", flag: "🇬🇹" },
  { country: "Guayana Francesa", code: "GF", prefix: "+594", flag: "🇬🇫" },
  { country: "Guernsey", code: "GG", prefix: "+44-1481", flag: "🇬🇬" },
  { country: "Guinea", code: "GN", prefix: "+224", flag: "🇬🇳" },
  { country: "Guinea-Bisáu", code: "GW", prefix: "+245", flag: "🇬🇼" },
  { country: "Guinea Ecuatorial", code: "GQ", prefix: "+240", flag: "🇬🇶" },
  { country: "Guyana", code: "GY", prefix: "+592", flag: "🇬🇾" },
  { country: "Haití", code: "HT", prefix: "+509", flag: "🇭🇹" },
  { country: "Honduras", code: "HN", prefix: "+504", flag: "🇭🇳" },
  { country: "Hong Kong", code: "HK", prefix: "+852", flag: "🇭🇰" },
  { country: "Hungría", code: "HU", prefix: "+36", flag: "🇭🇺" },
  { country: "India", code: "IN", prefix: "+91", flag: "🇮🇳" },
  { country: "Indonesia", code: "ID", prefix: "+62", flag: "🇮🇩" },
  { country: "Irak", code: "IQ", prefix: "+964", flag: "🇮🇶" },
  { country: "Irán", code: "IR", prefix: "+98", flag: "🇮🇷" },
  { country: "Irlanda", code: "IE", prefix: "+353", flag: "🇮🇪" },
  { country: "Isla de Man", code: "IM", prefix: "+44-1624", flag: "🇮🇲" },
  { country: "Islandia", code: "IS", prefix: "+354", flag: "🇮🇸" },
  { country: "Islas Caimán", code: "KY", prefix: "+1-345", flag: "🇰🇾" },
  { country: "Islas Cook", code: "CK", prefix: "+682", flag: "🇨🇰" },
  { country: "Islas Feroe", code: "FO", prefix: "+298", flag: "🇫🇴" },
  { country: "Islas Malvinas", code: "FK", prefix: "+500", flag: "🇫🇰" },
  {
    country: "Islas Marianas del Norte",
    code: "MP",
    prefix: "+1-670",
    flag: "🇲🇵",
  },
  { country: "Islas Marshall", code: "MH", prefix: "+692", flag: "🇲🇭" },
  { country: "Islas Salomón", code: "SB", prefix: "+677", flag: "🇸🇧" },
  {
    country: "Islas Turcas y Caicos",
    code: "TC",
    prefix: "+1-649",
    flag: "🇹🇨",
  },
  {
    country: "Islas Vírgenes Británicas",
    code: "VG",
    prefix: "+1-284",
    flag: "🇻🇬",
  },
  {
    country: "Islas Vírgenes de los EE.UU.",
    code: "VI",
    prefix: "+1-340",
    flag: "🇻🇮",
  },
  { country: "Israel", code: "IL", prefix: "+972", flag: "🇮🇱" },
  { country: "Italia", code: "IT", prefix: "+39", flag: "🇮🇹" },
  { country: "Jamaica", code: "JM", prefix: "+1-876", flag: "🇯🇲" },
  { country: "Japón", code: "JP", prefix: "+81", flag: "🇯🇵" },
  { country: "Jersey", code: "JE", prefix: "+44-1534", flag: "🇯🇪" },
  { country: "Jordania", code: "JO", prefix: "+962", flag: "🇯🇴" },
  { country: "Kazajistán", code: "KZ", prefix: "+7", flag: "🇰🇿" },
  { country: "Kenia", code: "KE", prefix: "+254", flag: "🇰🇪" },
  { country: "Kirguistán", code: "KG", prefix: "+996", flag: "🇰🇬" },
  { country: "Kiribati", code: "KI", prefix: "+686", flag: "🇰🇮" },
  { country: "Kuwait", code: "KW", prefix: "+965", flag: "🇰🇼" },
  { country: "Laos", code: "LA", prefix: "+856", flag: "🇱🇦" },
  { country: "Lesoto", code: "LS", prefix: "+266", flag: "🇱🇸" },
  { country: "Letonia", code: "LV", prefix: "+371", flag: "🇱🇻" },
  { country: "Líbano", code: "LB", prefix: "+961", flag: "🇱🇧" },
  { country: "Liberia", code: "LR", prefix: "+231", flag: "🇱🇷" },
  { country: "Libia", code: "LY", prefix: "+218", flag: "🇱🇾" },
  { country: "Liechtenstein", code: "LI", prefix: "+423", flag: "🇱🇮" },
  { country: "Lituania", code: "LT", prefix: "+370", flag: "🇱🇹" },
  { country: "Luxemburgo", code: "LU", prefix: "+352", flag: "🇱🇺" },
  { country: "Macao", code: "MO", prefix: "+853", flag: "🇲🇴" },
  { country: "Macedonia del Norte", code: "MK", prefix: "+389", flag: "🇲🇰" },
  { country: "Madagascar", code: "MG", prefix: "+261", flag: "🇲🇬" },
  { country: "Malasia", code: "MY", prefix: "+60", flag: "🇲🇾" },
  { country: "Malaui", code: "MW", prefix: "+265", flag: "🇲🇼" },
  { country: "Maldivas", code: "MV", prefix: "+960", flag: "🇲🇻" },
  { country: "Malí", code: "ML", prefix: "+223", flag: "🇲🇱" },
  { country: "Malta", code: "MT", prefix: "+356", flag: "🇲🇹" },
  { country: "Marruecos", code: "MA", prefix: "+212", flag: "🇲🇦" },
  { country: "Martinica", code: "MQ", prefix: "+596", flag: "🇲🇶" },
  { country: "Mauricio", code: "MU", prefix: "+230", flag: "🇲🇺" },
  { country: "Mauritania", code: "MR", prefix: "+222", flag: "🇲🇷" },
  { country: "Mayotte", code: "YT", prefix: "+262", flag: "🇾🇹" },
  { country: "México", code: "MX", prefix: "+52", flag: "🇲🇽" },
  { country: "Micronesia", code: "FM", prefix: "+691", flag: "🇫🇲" },
  { country: "Moldavia", code: "MD", prefix: "+373", flag: "🇲🇩" },
  { country: "Mónaco", code: "MC", prefix: "+377", flag: "🇲🇨" },
  { country: "Mongolia", code: "MN", prefix: "+976", flag: "🇲🇳" },
  { country: "Montenegro", code: "ME", prefix: "+382", flag: "🇲🇪" },
  { country: "Montserrat", code: "MS", prefix: "+1-664", flag: "🇲🇸" },
  { country: "Mozambique", code: "MZ", prefix: "+258", flag: "🇲🇿" },
  { country: "Namibia", code: "NA", prefix: "+264", flag: "🇳🇦" },
  { country: "Nauru", code: "NR", prefix: "+674", flag: "🇳🇷" },
  { country: "Nepal", code: "NP", prefix: "+977", flag: "🇳🇵" },
  { country: "Nicaragua", code: "NI", prefix: "+505", flag: "🇳🇮" },
  { country: "Níger", code: "NE", prefix: "+227", flag: "🇳🇪" },
  { country: "Nigeria", code: "NG", prefix: "+234", flag: "🇳🇬" },
  { country: "Niue", code: "NU", prefix: "+683", flag: "🇳🇺" },
  { country: "Noruega", code: "NO", prefix: "+47", flag: "🇳🇴" },
  { country: "Nueva Caledonia", code: "NC", prefix: "+687", flag: "🇳🇨" },
  { country: "Nueva Zelanda", code: "NZ", prefix: "+64", flag: "🇳🇿" },
  { country: "Omán", code: "OM", prefix: "+968", flag: "🇴🇲" },
  { country: "Países Bajos", code: "NL", prefix: "+31", flag: "🇳🇱" },
  { country: "Pakistán", code: "PK", prefix: "+92", flag: "🇵🇰" },
  { country: "Palaos", code: "PW", prefix: "+680", flag: "🇵🇼" },
  { country: "Palestina", code: "PS", prefix: "+970", flag: "🇵🇸" },
  { country: "Panamá", code: "PA", prefix: "+507", flag: "🇵🇦" },
  { country: "Papúa Nueva Guinea", code: "PG", prefix: "+675", flag: "🇵🇬" },
  { country: "Paraguay", code: "PY", prefix: "+595", flag: "🇵🇾" },
  { country: "Perú", code: "PE", prefix: "+51", flag: "🇵🇪" },
  { country: "Polinesia Francesa", code: "PF", prefix: "+689", flag: "🇵🇫" },
  { country: "Polonia", code: "PL", prefix: "+48", flag: "🇵🇱" },
  { country: "Portugal", code: "PT", prefix: "+351", flag: "🇵🇹" },
  { country: "Puerto Rico", code: "PR", prefix: "+1-787", flag: "🇵🇷" },
  { country: "Reino Unido", code: "GB", prefix: "+44", flag: "🇬🇧" },
  {
    country: "República Centroafricana",
    code: "CF",
    prefix: "+236",
    flag: "🇨🇫",
  },
  { country: "República Checa", code: "CZ", prefix: "+420", flag: "🇨🇿" },
  { country: "República del Congo", code: "CG", prefix: "+242", flag: "🇨🇬" },
  {
    country: "República Democrática del Congo",
    code: "CD",
    prefix: "+243",
    flag: "🇨🇩",
  },
  { country: "República Dominicana", code: "DO", prefix: "+1-809", flag: "🇩🇴" },
  { country: "Reunión", code: "RE", prefix: "+262", flag: "🇷🇪" },
  { country: "Ruanda", code: "RW", prefix: "+250", flag: "🇷🇼" },
  { country: "Rumanía", code: "RO", prefix: "+40", flag: "🇷🇴" },
  { country: "Rusia", code: "RU", prefix: "+7", flag: "🇷🇺" },
  { country: "Samoa", code: "WS", prefix: "+685", flag: "🇼🇸" },
  { country: "Samoa Americana", code: "AS", prefix: "+1-684", flag: "🇦🇸" },
  {
    country: "San Cristóbal y Nieves",
    code: "KN",
    prefix: "+1-869",
    flag: "🇰🇳",
  },
  { country: "San Marino", code: "SM", prefix: "+378", flag: "🇸🇲" },
  {
    country: "San Martín (Parte Francesa)",
    code: "MF",
    prefix: "+590",
    flag: "🇲🇫",
  },
  {
    country: "San Martín (Parte Neerlandesa)",
    code: "SX",
    prefix: "+1-721",
    flag: "🇸🇽",
  },
  { country: "San Pedro y Miquelón", code: "PM", prefix: "+508", flag: "🇵🇲" },
  {
    country: "San Vicente y las Granadinas",
    code: "VC",
    prefix: "+1-784",
    flag: "🇻🇨",
  },
  { country: "Santa Elena", code: "SH", prefix: "+290", flag: "🇸🇭" },
  { country: "Santa Lucía", code: "LC", prefix: "+1-758", flag: "🇱🇨" },
  { country: "Santo Tomé y Príncipe", code: "ST", prefix: "+239", flag: "🇸🇹" },
  { country: "Senegal", code: "SN", prefix: "+221", flag: "🇸🇳" },
  { country: "Serbia", code: "RS", prefix: "+381", flag: "🇷🇸" },
  { country: "Seychelles", code: "SC", prefix: "+248", flag: "🇸🇨" },
  { country: "Sierra Leona", code: "SL", prefix: "+232", flag: "🇸🇱" },
  { country: "Singapur", code: "SG", prefix: "+65", flag: "🇸🇬" },
  { country: "Siria", code: "SY", prefix: "+963", flag: "🇸🇾" },
  { country: "Somalia", code: "SO", prefix: "+252", flag: "🇸🇴" },
  { country: "Sri Lanka", code: "LK", prefix: "+94", flag: "🇱🇰" },
  { country: "Suazilandia (Eswatini)", code: "SZ", prefix: "+268", flag: "🇸🇿" },
  { country: "Sudáfrica", code: "ZA", prefix: "+27", flag: "🇿🇦" },
  { country: "Sudán", code: "SD", prefix: "+249", flag: "🇸🇩" },
  { country: "Sudán del Sur", code: "SS", prefix: "+211", flag: "🇸🇸" },
  { country: "Suecia", code: "SE", prefix: "+46", flag: "🇸🇪" },
  { country: "Suiza", code: "CH", prefix: "+41", flag: "🇨🇭" },
  { country: "Surinam", code: "SR", prefix: "+597", flag: "🇸🇷" },
  { country: "Tailandia", code: "TH", prefix: "+66", flag: "🇹🇭" },
  { country: "Taiwán", code: "TW", prefix: "+886", flag: "🇹🇼" },
  { country: "Tanzania", code: "TZ", prefix: "+255", flag: "🇹🇿" },
  { country: "Tayikistán", code: "TJ", prefix: "+992", flag: "🇹🇯" },
  { country: "Timor Oriental", code: "TL", prefix: "+670", flag: "🇹🇱" },
  { country: "Togo", code: "TG", prefix: "+228", flag: "🇹🇬" },
  { country: "Tokelau", code: "TK", prefix: "+690", flag: "🇹🇰" },
  { country: "Tonga", code: "TO", prefix: "+676", flag: "🇹🇴" },
  { country: "Trinidad y Tobago", code: "TT", prefix: "+1-868", flag: "🇹🇹" },
  { country: "Túnez", code: "TN", prefix: "+216", flag: "🇹🇳" },
  { country: "Turkmenistán", code: "TM", prefix: "+993", flag: "🇹🇲" },
  { country: "Turquía", code: "TR", prefix: "+90", flag: "🇹🇷" },
  { country: "Tuvalu", code: "TV", prefix: "+688", flag: "🇹🇻" },
  { country: "Ucrania", code: "UA", prefix: "+380", flag: "🇺🇦" },
  { country: "Uganda", code: "UG", prefix: "+256", flag: "🇺🇬" },
  { country: "Uruguay", code: "UY", prefix: "+598", flag: "🇺🇾" },
  { country: "Uzbekistán", code: "UZ", prefix: "+998", flag: "🇺🇿" },
  { country: "Vanuatu", code: "VU", prefix: "+678", flag: "🇻🇺" },
  { country: "Venezuela", code: "VE", prefix: "+58", flag: "🇻🇪" },
  { country: "Vietnam", code: "VN", prefix: "+84", flag: "🇻🇳" },
  { country: "Wallis y Futuna", code: "WF", prefix: "+681", flag: "🇼🇫" },
  { country: "Yemen", code: "YE", prefix: "+967", flag: "🇾🇪" },
  { country: "Yibuti", code: "DJ", prefix: "+253", flag: "🇩🇯" },
  { country: "Zambia", code: "ZM", prefix: "+260", flag: "🇿🇲" },
  { country: "Zimbabue", code: "ZW", prefix: "+263", flag: "🇿🇼" },
];