export const DISTRICTS = [
  { label: "Ancón", value: "ancon" },
  { label: "Ate", value: "ate" },
  { label: "Barranco", value: "barranco" },
  { label: "Breña", value: "brena" },
  { label: "Carabayllo", value: "carabayllo" },
  { label: "Cercado de Lima", value: "cercado_de_lima" },
  { label: "Chaclacayo", value: "chaclacayo" },
  { label: "Chorrillos", value: "chorrillos" },
  { label: "Cieneguilla", value: "cieneguilla" },
  { label: "Comas", value: "comas" },
  { label: "El Agustino", value: "el_agustino" },
  { label: "Independencia", value: "independencia" },
  { label: "Jesús María", value: "jesus_maria" },
  { label: "La Molina", value: "la_molina" },
  { label: "La Victoria", value: "la_victoria" },
  { label: "Lince", value: "lince" },
  { label: "Los Olivos", value: "los_olivos" },
  { label: "Lurigancho", value: "lurigancho" },
  { label: "Lurín", value: "lurin" },
  { label: "Magdalena del Mar", value: "magdalena_del_mar" },
  { label: "Miraflores", value: "miraflores" },
  { label: "Pachacámac", value: "pachacamac" },
  { label: "Pucusana", value: "pucusana" },
  { label: "Pueblo Libre", value: "pueblo_libre" },
  { label: "Puente Piedra", value: "puente_piedra" },
  { label: "Punta Hermosa", value: "punta_hermosa" },
  { label: "Punta Negra", value: "punta_negra" },
  { label: "Rímac", value: "rimac" },
  { label: "San Bartolo", value: "san_bartolo" },
  { label: "San Borja", value: "san_borja" },
  { label: "San Isidro", value: "san_isidro" },
  { label: "San Juan de Lurigancho", value: "san_juan_de_lurigancho" },
  { label: "San Juan de Miraflores", value: "san_juan_de_miraflores" },
  { label: "San Luis", value: "san_luis" },
  { label: "San Martín de Porres", value: "san_martin_de_porres" },
  { label: "San Miguel", value: "san_miguel" },
  { label: "Santa Anita", value: "santa_anita" },
  { label: "Santa María del Mar", value: "santa_maria_del_mar" },
  { label: "Santa Rosa", value: "santa_rosa" },
  { label: "Santiago de Surco", value: "santiago_de_surco" },
  { label: "Surquillo", value: "surquillo" },
  { label: "Villa El Salvador", value: "villa_el_salvador" },
  { label: "Villa María del Triunfo", value: "villa_maria_del_triunfo" },
];