import {
  AlertTriangle,
  AppWindow,
  BatteryCharging,
  BatteryMedium,
  Bug,
  Camera,
  CameraOff,
  Cctv,
  Circle,
  CircleDot,
  CircuitBoard,
  Cpu,
  Database,
  Droplet,
  Droplets,
  Flame,
  Focus,
  GlassWater,
  Grid3X3,
  HandMetal,
  History,
  Keyboard,
  KeyRound,
  Layers,
  Lightbulb,
  LightbulbOff,
  MicOff,
  Microchip,
  Monitor,
  MonitorDot,
  MonitorOff,
  MonitorX,
  Palette,
  PencilRuler,
  PhoneCall,
  PlugZap,
  PowerOff,
  RefreshCw,
  ScanLine,
  Server,
  Settings2,
  ShieldAlert,
  SignalLow,
  Smartphone,
  SmartphoneNfc,
  SplitSquareVertical,
  TabletSmartphone,
  Thermometer,
  ThermometerSun,
  Unlock,
  Usb,
  Waves,
  WifiOff,
  Zap,
  ZapOff,
} from "lucide-react";

export const SERVICES_DATA = [
  {
    type: "liquid-spill",
    typeSpeciality: "laptop-repair",
    slug: "reparacion-por-derrame-de-liquido",
    title: "Derrame de líquido",
    icon: Droplets,
    description:
      "Limpieza ultrasónica y reparación de circuitos afectados por humedad.",
    longDescription:
      "Brindamos un servicio avanzado de rescate para laptops afectadas por líquidos. Utilizamos cubas de ultrasonido con soluciones químicas dieléctricas para remover la sulfatación bajo los chips BGA.",
    image: "/assets/images/services/liquid-spill.png",
    includes: [
      "Desoxidación por ultrasonido",
      "Secado térmico controlado",
      "Re-estuñado de pistas corroídas",
    ],
    technicalData:
      "Uso de alcohol isopropílico 99% y estaciones de secado ESD.",
  },
  {
    type: "virus-malware-issues",
    typeSpeciality: "laptop-repair",
    slug: "eliminacion-de-virus-y-malware",
    title: "Problema de virus",
    icon: ShieldAlert,
    description: "Detección y eliminación de malware, troyanos y spyware.",
    longDescription:
      "Realizamos un escaneo profundo de bajo nivel para eliminar virus, troyanos y spyware que causan corrupción de datos.",
    image: "/assets/images/services/virus-malware-issues.png",
    includes: [
      "Escaneo heurístico de seguridad",
      "Eliminación de Malware",
      "Optimización de registro",
    ],
    technicalData: "Desinfección sin pérdida de archivos.",
  },
  {
    type: "only-leds-on",
    typeSpeciality: "laptop-repair",
    slug: "reparacion-encendido-led",
    title: "Solo encienden los LED",
    icon: LightbulbOff,
    description:
      "Diagnóstico para equipos que encienden pero no muestran imagen.",
    longDescription:
      "Analizamos el Power Sequence, verificamos voltajes en bobinas y realizamos reprogramación de BIOS/SMC.",
    image: "/assets/images/services/only-leds-on.png",
    includes: [
      "Diagnóstico Nivel 3",
      "Reprogramación BIOS/EEPROM",
      "Revisión de voltajes",
    ],
    technicalData: "Medición con osciloscopio y multímetro de precisión.",
  },
  {
    type: "overheating",
    typeSpeciality: "laptop-repair",
    slug: "mantenimiento-por-sobrecalentamiento",
    title: "Sobrecalentamiento",
    icon: ThermometerSun,
    description:
      "Mantenimiento preventivo para evitar daños por exceso de calor.",
    longDescription:
      "Sustituimos pasta térmica seca por compuestos de alta conductividad y renovamos thermal pads.",
    image: "/assets/images/services/overheating.png",
    includes: [
      "Limpieza de ventiladores",
      "Cambio de pasta térmica (>8.5 W/mK)",
      "Renovación de Thermal Pads",
    ],
    technicalData: "Pasta térmica de grado industrial.",
  },
  {
    type: "operating-system-failure",
    typeSpeciality: "laptop-repair",
    slug: "reparacion-sistema-operativo",
    title: "Fallas en Sistema",
    icon: AppWindow,
    description: "Solución a pantallas azules y bloqueos de Windows o MacOS.",
    longDescription:
      "Corregimos problemas críticos del software, desde BSOD hasta bucles de reinicio.",
    image: "/assets/images/services/operating-system-failure.png",
    includes: [
      "Reparación de arranque",
      "Instalación de drivers",
      "Optimización de registro",
    ],
    technicalData: "Soporte para Windows 11 y macOS.",
  },
  {
    type: "broken-hinges",
    typeSpeciality: "laptop-repair",
    slug: "reparacion-de-laptops",
    title: "Bisagras quebradas",
    icon: PencilRuler,
    description: "Reconstrucción y cambio de bisagras y carcasas dañadas.",
    longDescription:
      "Reconstrucción de anclajes mediante resinas epóxicas de grado industrial.",
    image: "/assets/images/services/broken-hinges.png",
    includes: [
      "Reconstrucción de soportes",
      "Cambio de bisagras metálicas",
      "Refuerzo estructural",
    ],
    technicalData: "Uso de polímeros de alta resistencia.",
  },
  {
    type: "broken-screen",
    typeSpeciality: "laptop-repair",
    slug: "cambio-de-pantalla-laptop",
    title: "Pantalla Quebrada",
    icon: MonitorX,
    description: "Sustitución inmediata de pantallas LED/LCD todas las marcas.",
    longDescription:
      "Cambio de pantallas dañadas siguiendo protocolos de seguridad antiestática.",
    image: "/assets/images/services/broken-screen.png",
    includes: [
      "Repuestos originales OEM",
      "Instalación antiestática",
      "Garantía de color",
    ],
    technicalData: "Paneles Grado A+.",
  },
  {
    type: "keyboard-failure",
    typeSpeciality: "laptop-repair",
    slug: "reparacion-de-teclado",
    title: "Falla de teclado",
    icon: Keyboard,
    description:
      "Reparación y cambio de teclados para laptops de todas las gamas.",
    longDescription:
      "Trabajamos con teclados remachados, retroiluminados y mecánicos.",
    image: "/assets/images/services/keyboard-failure.png",
    includes: [
      "Cambio de teclado",
      "Limpieza de membrana",
      "Pruebas de pulsación",
    ],
    technicalData: "Repuestos originales en español e inglés.",
  },
  {
    type: "port-failure",
    typeSpeciality: "laptop-repair",
    slug: "reparacion-puertos-usb-carga",
    title: "Puertos no funcionan",
    icon: Usb,
    description: "Reparación de puertos USB, HDMI y conectores de carga.",
    longDescription:
      "Reparamos soldaduras frías y pines fracturados en USB-C y DC Jacks.",
    image: "/assets/images/services/port-failure.png",
    includes: [
      "Micro-soldadura SMD",
      "Cambio de Jack de carga",
      "Reparación HDMI/USB-C",
    ],
    technicalData: "Soldadura con aleación de plata.",
  },
  {
    type: "audio-microphone-failure",
    typeSpeciality: "smartphone-repair",
    slug: "falla-microfono-audio-smartphone",
    title: "Falla en micrófono",
    icon: MicOff,
    description:
      "Reparación de problemas de audio y micrófonos en iPhone/Galaxy.",
    longDescription:
      "Cambio de módulos de micrófono y reparación de códecs de audio en placa.",
    image: "/assets/images/services/audio-microphone-failure.png",
    includes: [
      "Cambio de micrófono",
      "Reparación de Codec Audio",
      "Limpieza acústica",
    ],
    technicalData: "Calibración de cancelación de ruido.",
  },
  {
    type: "smartphone-overheating",
    typeSpeciality: "smartphone-repair",
    slug: "sobrecalentamiento-smartphone",
    title: "Recalentamiento móvil",
    icon: Flame,
    description: "Diagnóstico para equipos que calientan de forma anormal.",
    longDescription:
      "Uso de cámaras térmicas para localizar componentes en corto en la placa base.",
    image: "/assets/images/services/smartphone-overheating.png",
    includes: ["Cámara térmica", "Consumo de batería", "Detección de fugas"],
    technicalData: "Análisis de consumo en mA en tiempo real.",
  },
  {
    type: "broken-home-button",
    typeSpeciality: "smartphone-repair",
    slug: "boton-home-danado",
    title: "Botón Home dañado",
    icon: CircleDot,
    description: "Reparación de botones de inicio que no responden.",
    longDescription:
      "Cambio de membrana táctil o flex de conexión para recuperar la sensibilidad.",
    image: "/assets/images/services/broken-home-button.png",
    includes: [
      "Reemplazo de flex",
      "Ajuste de presión",
      "Pruebas de respuesta",
    ],
    technicalData: "Sellado preventivo contra polvo.",
  },
  {
    type: "broken-touch-lcd",
    typeSpeciality: "smartphone-repair",
    slug: "touch-quebrado-iphone-galaxy",
    title: "Touch quebrado",
    icon: SmartphoneNfc,
    description: "Sustitución de cristal táctil para equipos con cristal roto.",
    longDescription:
      "Laminación al vacío (OCA) para adherir el nuevo cristal al LCD original.",
    image: "/assets/images/services/broken-touch-lcd.png",
    includes: [
      "Cambio de cristal",
      "Laminación OCA",
      "Calibración de sensibilidad",
    ],
    technicalData: "Adhesivos de grado original.",
  },
  {
    type: "charging-port-failure",
    typeSpeciality: "smartphone-repair",
    slug: "problemas-jack-puerto-carga",
    title: "Falla de puerto carga",
    icon: Zap,
    description: "Reparación de puertos que no cargan o no sincronizan.",
    longDescription:
      "Cambio técnico del flex de carga compatible con carga rápida.",
    image: "/assets/images/services/charging-port-failure.png",
    includes: [
      "Cambio de flex de carga",
      "Limpieza de puerto",
      "Pruebas de datos",
    ],
    technicalData: "Certificación de transferencia de datos.",
  },
  {
    type: "liquid-contact",
    typeSpeciality: "smartphone-repair",
    slug: "contacto-con-liquidos-smartphone",
    title: "Móvil mojado",
    icon: Waves,
    description: "Tratamiento de deshumidificación para equipos mojados.",
    longDescription:
      "Limpieza ultrasónica y deshumidificación al vacío para detener la corrosión.",
    image: "/assets/images/services/liquid-contact.png",
    includes: [
      "Limpieza ultrasónica",
      "Deshumidificación",
      "Anticorrosivo químico",
    ],
    technicalData: "Éxito >85% en las primeras 24h.",
  },
  {
    type: "battery-issues",
    typeSpeciality: "smartphone-repair",
    slug: "problemas-bateria-smartphone",
    title: "Falla de batería",
    icon: BatteryMedium,
    description: "Cambio de baterías que duran poco o no cargan.",
    longDescription:
      "Instalación de celdas de alta densidad para autonomía original.",
    image: "/assets/images/services/battery-issues.png",
    includes: [
      "Sustitución Li-ion",
      "Pruebas de ciclos",
      "Garantía de autonomía",
    ],
    technicalData: "Celdas con protección contra sobrecarga.",
  },
  {
    type: "camera-failure",
    typeSpeciality: "smartphone-repair",
    slug: "problemas-camara-smartphone",
    title: "Problema de cámara",
    icon: CameraOff,
    description: "Reparación de cámaras pixeleadas o que no abren.",
    longDescription:
      "Cambio del módulo óptico original para restaurar enfoque y nitidez.",
    image: "/assets/images/services/camera-failure.png",
    includes: ["Módulo OEM", "Limpieza de lente", "Pruebas de OIS"],
    technicalData: "Soporte para estabilización óptica.",
  },
  {
    type: "wifi-connectivity-failure",
    typeSpeciality: "smartphone-repair",
    slug: "problemas-wifi-cobertura",
    title: "Sin señal WIFI",
    icon: WifiOff,
    description: "Solución a problemas de pérdida de cobertura inalámbrica.",
    longDescription:
      "Micro-soldadura en el sector de radiofrecuencia (Baseband/Antenas).",
    image: "/assets/images/services/wifi-connectivity-failure.png",
    includes: [
      "Reparación de antena",
      "Soldadura chip WiFi",
      "Análisis de señal",
    ],
    technicalData: "Medición de ganancia en dBm.",
  },
  {
    type: "broken-lcd",
    typeSpeciality: "smartphone-repair",
    slug: "lcd-quebrado-smartphone",
    title: "LCD con manchas",
    icon: TabletSmartphone,
    description: "Sustitución de pantalla interna para equipos sin imagen.",
    longDescription:
      "Cambio de módulo OLED/LCD grado original para brillo y resolución nativa.",
    image: "/assets/images/services/broken-lcd.png",
    includes: [
      "Cambio Display completo",
      "Calibración True Tone",
      "Sellado IP68",
    ],
    technicalData: "Paneles Super Retina y AMOLED.",
  },
  {
    type: "reboot-loop-issue",
    typeSpeciality: "smartphone-repair",
    slug: "smartphone-se-reinicia",
    title: "Bucle de reinicio",
    icon: RefreshCw,
    description: "Diagnóstico de equipos pegados en el logo.",
    longDescription:
      "Restauración de firmware y diagnóstico de hardware en memoria flash.",
    image: "/assets/images/services/reboot-loop-issue.png",
    includes: ["Restauración DFU", "Diagnóstico NAND", "Análisis de Logs"],
    technicalData: "Especialistas en errores 4013 y 9.",
  },
  {
    type: "broken-touch-screen",
    typeSpeciality: "tablet-repair",
    slug: "pantalla-touch-quebrada-tablet",
    title: "Touch Tablet roto",
    icon: SplitSquareVertical,
    description: "Reemplazo del cristal exterior para iPad o Galaxy Tab.",
    longDescription:
      "Cambio de digitalizador con adhesivos estructurales originales.",
    image: "/assets/images/services/broken-touch-screen.png",
    includes: ["Cambio digitalizador", "Limpieza interna", "Pruebas Stylus"],
    technicalData: "Cristal templado de alta resistencia.",
  },
  {
    type: "touch-lcd-damage",
    typeSpeciality: "tablet-repair",
    slug: "touch-lcd-quebrado-ipad",
    title: "Módulo Tablet dañado",
    icon: Smartphone,
    description: "Sustitución de visualizador y táctil completo.",
    longDescription:
      "Sustitución integral del módulo laminado para evitar entrada de polvo.",
    image: "/assets/images/services/touch-lcd-damage.png",
    includes: [
      "Reemplazo módulo completo",
      "Sellado perimetral",
      "Calibración color",
    ],
    technicalData: "Pantallas Liquid Retina originales.",
  },
  {
    type: "touch-malfunction",
    typeSpeciality: "tablet-repair",
    slug: "falla-touch-ipad-tablet",
    title: "Touch no responde",
    icon: HandMetal,
    description: "Reparación de pantallas que se congelan o no responden.",
    longDescription:
      "Diagnóstico de Touch IC en placa base o flexores dañados.",
    image: "/assets/images/services/touch-malfunction.png",
    includes: [
      "Diagnóstico Touch IC",
      "Revisión de flexores",
      "Pruebas multitoque",
    ],
    technicalData: "Reparación a nivel micro-componente.",
  },
  {
    type: "liquid-accident",
    typeSpeciality: "tablet-repair",
    slug: "accidente-liquidos-tablet",
    title: "Tablet mojada",
    icon: GlassWater,
    description: "Tratamiento de emergencia para tablets sumergidas.",
    longDescription:
      "Apertura inmediata y limpieza química para evitar corrosión de batería.",
    image: "/assets/images/services/liquid-accident.png",
    includes: [
      "Secado gran formato",
      "Limpieza ultrasónica",
      "Pruebas de consumo",
    ],
    technicalData: "Químicos deshumidificantes grado electrónico.",
  },
  {
    type: "home-button-repair",
    typeSpeciality: "tablet-repair",
    slug: "reparacion-boton-home-tablet",
    title: "Botón Home Tablet",
    icon: Circle,
    description: "Corrección de botones de inicio atascados.",
    longDescription: "Reparación de membrana de presión para respuesta fluida.",
    image: "/assets/images/services/home-button-repair.png",
    includes: [
      "Sustitución flex Home",
      "Limpieza contactos",
      "Ajuste presión original",
    ],
    technicalData: "Repuestos originales alta durabilidad.",
  },
  {
    type: "battery-replacement",
    typeSpeciality: "tablet-repair",
    slug: "cambio-bateria-tablet",
    title: "Cambio batería Tablet",
    icon: BatteryCharging,
    description: "Sustitución de baterías agotadas o infladas.",
    longDescription:
      "Verificación de IC de carga (Tristar/U2) para asegurar ciclos sanos.",
    image: "/assets/images/services/battery-replacement.png",
    includes: [
      "Sustitución batería",
      "Diagnóstico IC Carga",
      "Calibración porcentaje",
    ],
    technicalData: "Celdas Li-Po certificadas.",
  },
  {
    type: "auto-reboot-issue",
    typeSpeciality: "tablet-repair",
    slug: "se-reinicia-sola-tablet",
    title: "Bucle reinicio Tablet",
    icon: History,
    description: "Solución para iPads que se quedan en pantalla negra.",
    longDescription:
      "Reparación de arranque (Boot Repair) y restauración de firmware.",
    image: "/assets/images/services/auto-reboot-issue.png",
    includes: ["Restauración firmware", "Boot Repair", "Estabilidad sistema"],
    technicalData: "Soporte iPadOS y Android.",
  },
  {
    type: "deformation-swollen-battery",
    typeSpeciality: "tablet-repair",
    slug: "deformacion-ipad-tablet",
    title: "Chasis deformado",
    icon: Layers,
    description: "Reparación de equipos deformados por batería hinchada.",
    longDescription:
      "Extracción segura de batería y alineación técnica de chasis de aluminio.",
    image: "/assets/images/services/deformation-swollen-battery.png",
    includes: [
      "Extracción segura",
      "Alineación de chasis",
      "Revisión integridad",
    ],
    technicalData: "Protocolo de manejo de baterías inflamadas.",
  },
  {
    type: "unlocking-service",
    typeSpeciality: "tablet-repair",
    slug: "desbloqueo-ipad-tablet",
    title: "Desbloqueo de Tablet",
    icon: Unlock,
    description:
      "Servicio técnico para recuperar el acceso a equipos bloqueados.",
    longDescription:
      "Realizamos procesos de restauración técnica para devolverte el control de tu dispositivo bajo protocolos de seguridad.",
    image: "/assets/images/services/unlocking-service.png",
    includes: [
      "Restablecimiento de OS",
      "Remoción de códigos",
      "Actualización de versión",
    ],
    technicalData:
      "Proceso mediante software de servicio técnico especializado.",
  },
  {
    type: "camera-issues",
    typeSpeciality: "tablet-repair",
    slug: "problemas-camara-tablet",
    title: "Problemas en cámara",
    icon: Camera,
    description: "Reparación de cámaras que toman fotos borrosas o no abren.",
    longDescription:
      "Cambio del módulo de cámara frontal o trasera, asegurando nitidez y calidad HD original.",
    image: "/assets/images/services/camera-issues.png",
    includes: [
      "Sustitución de módulo",
      "Limpieza de lente",
      "Pruebas de enfoque (AF)",
    ],
    technicalData: "Sensores originales con soporte 4K/FHD.",
  },
  {
    type: "port-connector-failure",
    typeSpeciality: "tablet-repair",
    slug: "problemas-puertos-tablet",
    title: "Problemas en puertos",
    icon: PlugZap,
    description: "Reparación o sustitución de puertos de carga y Jacks.",
    longDescription:
      "Sustitución de conectores Lightning o USB-C mediante micro-soldadura reforzada.",
    image: "/assets/images/services/port-connector-failure.png",
    includes: [
      "Cambio conector carga",
      "Reparación Jack 3.5mm",
      "Refuerzo de soldadura",
    ],
    technicalData: "Soldadura con aleación industrial de alta resistencia.",
  },
  {
    type: "video-distortion",
    typeSpeciality: "projector-repair",
    slug: "distorsion-de-video-proyector",
    title: "Distorsión de vídeo",
    icon: Palette,
    description: "Corrección de imágenes deformadas o colores alterados.",
    longDescription:
      "Calibramos la convergencia óptica y reparamos la rueda de color o paneles LCD internos.",
    image: "/assets/images/services/video-distortion.png",
    includes: [
      "Calibración óptica",
      "Limpieza rueda color",
      "Ajuste paneles LCD",
    ],
    technicalData: "Calibración bajo estándar Rec.709.",
  },
  {
    type: "blurry-image",
    typeSpeciality: "projector-repair",
    slug: "imagen-borrosa-proyector",
    title: "Imagen borrosa",
    icon: Focus,
    description: "Limpieza y ajuste de lentes para recuperar la nitidez.",
    longDescription:
      "Limpieza profunda del bloque óptico sellado y ajuste del mecanismo de enfoque/zoom.",
    image: "/assets/images/services/blurry-image.png",
    includes: [
      "Limpieza de prismas",
      "Ajuste espejos dicroicos",
      "Lubricación de zoom",
    ],
    technicalData: "Limpieza con solventes ópticos especializados.",
  },
  {
    type: "dotted-image",
    typeSpeciality: "projector-repair",
    slug: "imagen-con-puntos-proyector",
    title: "Imagen con puntos",
    icon: Grid3X3,
    description:
      "Reparación de fallas de píxeles o puntos blancos (Efecto Galaxia).",
    longDescription:
      "Reemplazo del chip DMD dañado y renovación del sistema de disipación térmica.",
    image: "/assets/images/services/dotted-image.png",
    includes: [
      "Sustitución Chip DMD",
      "Cambio pasta térmica",
      "Limpieza sensores",
    ],
    technicalData: "Stock de chips DMD para modelos 800x600 hasta 4K.",
  },
  {
    type: "no-signal-message",
    typeSpeciality: "projector-repair",
    slug: "mensaje-sin-senal-proyector",
    title: "Sin señal",
    icon: SignalLow,
    description: "Solución a problemas de conectividad en puertos HDMI o VGA.",
    longDescription:
      "Reparamos puertos fracturados o chips controladores de video dañados en la Mainboard.",
    image: "/assets/images/services/no-signal-message.png",
    includes: [
      "Reparación HDMI/VGA",
      "Diagnóstico chip escalador",
      "Pruebas EDID",
    ],
    technicalData: "Soporte para protocolos HDCP y señales digitales.",
  },
  {
    type: "auto-shutdown-reboot",
    typeSpeciality: "projector-repair",
    slug: "proyector-se-apaga-o-reinicia",
    title: "Apagados repentinos",
    icon: PowerOff,
    description: "Diagnóstico de fallas eléctricas y sensores de temperatura.",
    longDescription:
      "Revisamos la fuente de poder (Ballast) y el sistema de ventiladores de enfriamiento.",
    image: "/assets/images/services/auto-shutdown-reboot.png",
    includes: [
      "Revisión fuente poder",
      "Limpieza ventiladores",
      "Prueba sensores térmicos",
    ],
    technicalData: "Monitoreo de curvas de temperatura interna.",
  },
  {
    type: "lamp-failure",
    typeSpeciality: "projector-repair",
    slug: "falla-lampara-proyector",
    title: "¿Falla la lámpara?",
    icon: Lightbulb,
    description: "Cambio de lámparas originales y reseteo de contadores.",
    longDescription:
      "Instalamos lámparas originales de alta luminosidad (UHP/Mercurio) con garantía de brillo.",
    image: "/assets/images/services/lamp-failure.png",
    includes: [
      "Lámpara certificada OEM",
      "Reseteo de horas",
      "Limpieza de filtros",
    ],
    technicalData: "Lámparas con garantía de durabilidad.",
  },
  {
    type: "projector-overheating",
    typeSpeciality: "projector-repair",
    slug: "sobrecalentamiento-proyector",
    title: "Recalentamiento",
    icon: Thermometer,
    description:
      "Servicio de enfriamiento para evitar que los componentes se fundan.",
    longDescription:
      "Limpieza química de filtros y lubricación de turbinas para optimizar el flujo de aire (CFM).",
    image: "/assets/images/services/projector-overheating.png",
    includes: [
      "Limpieza profunda",
      "Lubricación de turbinas",
      "Pruebas prolongadas",
    ],
    technicalData: "Optimización del flujo de aire interno.",
  },
  {
    type: "forgotten-password",
    typeSpeciality: "all-in-one-repair",
    slug: "recuperacion-contrasena-pc-all-in-one",
    title: "Recuperar Contraseña",
    icon: KeyRound,
    description: "Acceso a tu All-in-One bloqueada por credenciales.",
    longDescription:
      "Recuperamos acceso a OS o BIOS mediante herramientas de bajo nivel sin formatear.",
    image: "/assets/images/services/forgotten-password.png",
    includes: [
      "Reset Windows/Mac",
      "Desbloqueo BIOS/UEFI",
      "Recuperación de cuentas",
    ],
    technicalData: "Procedimientos seguros bajo autorización legal.",
  },
  {
    type: "blue-screen-error",
    typeSpeciality: "all-in-one-repair",
    slug: "reparacion-pantalla-azul-aio",
    title: "Pantalla Azul (BSOD)",
    icon: MonitorDot,
    description: "Solución a errores críticos, lentitud y bloqueos constantes.",
    longDescription:
      "Diagnóstico de RAM, sectores de disco y optimización de drivers compatibles.",
    image: "/assets/images/services/blue-screen-error.png",
    includes: [
      "Diagnóstico de Logs",
      "Optimización de OS",
      "Actualización drivers",
    ],
    technicalData: "Análisis de volcados de memoria (Dumps).",
  },
  {
    type: "motherboard-repair",
    typeSpeciality: "all-in-one-repair",
    slug: "reparacion-placa-madre-aio",
    title: "Reparación de Placas AIO",
    icon: Cpu,
    description:
      "Micro-soldadura avanzada para fallas complejas en la motherboard.",
    longDescription:
      "Reemplazo de condensadores sólidos y MOSFETs de la etapa de potencia.",
    image: "/assets/images/services/motherboard-repair.png",
    includes: [
      "Micro-soldadura SMD",
      "Diagnóstico precisión",
      "Cambio integrados",
    ],
    technicalData: "Reparación electrónica Nivel 3.",
  },
  {
    type: "no-video-output",
    typeSpeciality: "all-in-one-repair",
    slug: "falla-imagen-video-aio",
    title: "Sin Imagen AIO",
    icon: MonitorOff,
    description: "Diagnóstico de equipos que encienden pero no muestran video.",
    longDescription:
      "Revisión de chip gráfico (GPU), cable flex y etapa de retroiluminación (Backlight).",
    image: "/assets/images/services/no-video-output.png",
    includes: [
      "Revisión GPU",
      "Pruebas pantalla interna",
      "Reparación cable Flex",
    ],
    technicalData: "Pruebas de salida secundaria HDMI/DP.",
  },
  {
    type: "damaged-aio-screen",
    typeSpeciality: "all-in-one-repair",
    slug: "cambio-pantalla-dañada-aio",
    title: "Pantalla AIO Quebrada",
    icon: Monitor,
    description: "Sustitución de paneles LED/LCD para computadoras All-in-One.",
    longDescription:
      "Importación directa de paneles para asegurar acabado original y sellado perimetral.",
    image: "/assets/images/services/damaged-aio-screen.png",
    includes: [
      "Repuestos originales",
      "Instalación precisión",
      "Garantía de color",
    ],
    technicalData: "Paneles LED/IPS de alta resolución.",
  },
  {
    type: "auto-power-off",
    typeSpeciality: "all-in-one-repair",
    slug: "pc-all-in-one-se-apaga",
    title: "AIO se apaga sola",
    icon: AlertTriangle,
    description:
      "Reparación de fallas en fuente de poder o saturación térmica.",
    longDescription:
      "Diagnóstico profundo de la etapa de carga y sistema de ventilación forzada.",
    image: "/assets/images/services/auto-power-off.png",
    includes: [
      "Revisión fuente interna",
      "Mantenimiento térmico",
      "Detección de fugas",
    ],
    technicalData: "Análisis de eficiencia de fuentes conmutadas.",
  },
  {
    type: "virus-cleaning-aio",
    typeSpeciality: "all-in-one-repair",
    slug: "limpieza-virus-malware-aio",
    title: "Limpieza de Virus AIO",
    icon: Bug,
    description: "Eliminación de amenazas sin perder archivos personales.",
    longDescription:
      "Limpieza de malware y troyanos incluso en el sector de arranque (Boot).",
    image: "/assets/images/services/virus-cleaning-aio.png",
    includes: [
      "Eliminación Malware",
      "Respaldo preventivo",
      "Instalación seguridad",
    ],
    technicalData: "Remoción de Ransomware y Rootkits.",
  },
  {
    type: "aio-overheating",
    typeSpeciality: "all-in-one-repair",
    slug: "sobrecalentamiento-pc-aio",
    title: "Calentamiento AIO",
    icon: Thermometer,
    description: "Limpieza interna y cambio de pasta térmica premium.",
    longDescription:
      "Bajamos la temperatura operativa hasta 20°C mediante compuestos de plata.",
    image: "/assets/images/services/aio-overheating.png",
    includes: [
      "Limpieza disipadores",
      "Pasta térmica premium",
      "Lubricación ventilador",
    ],
    technicalData: "Conductividad térmica >5 W/mK.",
  },
  {
    type: "dead-pc-repair",
    typeSpeciality: "all-in-one-repair",
    slug: "pc-aio-no-enciende",
    title: "No Enciende AIO",
    icon: ZapOff,
    description:
      "Reparación de equipos con cortocircuitos o sin signos de vida.",
    longDescription:
      "Detección de fallas en integrados de 3V/5V y fuentes secundarias.",
    image: "/assets/images/services/dead-pc-repair.png",
    includes: ["Detección cortos", "Diagnóstico carga", "Sustitución quemados"],
    technicalData: "Uso de fuentes de laboratorio reguladas.",
  },
  {
    type: "hard-drive-data-recovery",
    typeSpeciality: "data-recovery",
    slug: "recuperacion-de-datos-disco-duro",
    title: "Recuperación de Datos",
    icon: Database,
    description: "Rescate de información en HDD y SSD con fallas físicas.",
    longDescription:
      "Clonación forense de sectores dañados y reconstrucción de particiones.",
    image: "/assets/images/services/hard-drive-data-recovery.png",
    includes: [
      "Clonación sectores",
      "Recuperación borrados",
      "Rescate particiones",
    ],
    technicalData: "Tasa de éxito >90% en fallas lógicas.",
  },
  {
    type: "server-and-network-maintenance",
    typeSpeciality: "servers-and-network-maintenance",
    slug: "mantenimiento-de-servidores-y-redes",
    title: "Servidores y Redes",
    icon: Server,
    description: "Soporte técnico para infraestructuras corporativas.",
    longDescription:
      "Mantenimiento de hardware, arreglos RAID y gestión de redes VLAN.",
    image: "/assets/images/services/server-and-network-maintenance.png",
    includes: [
      "Mantenimiento Servidores",
      "Configuración RAID",
      "Gestión VLAN/LAN",
    ],
    technicalData: "Soporte Windows Server y Linux.",
  },
  {
    type: "chipset-reballing",
    typeSpeciality: "reballing",
    slug: "servicio-de-reballing-profesional",
    title: "Servicio Reballing",
    icon: Microchip,
    description: "Diagnóstico especializado para fallas de video o encendido.",
    longDescription:
      "Sustitución de esferas de soldadura BGA mediante estaciones infrarrojas.",
    image: "/assets/images/services/chipset-reballing.png",
    includes: [
      "Extracción chip BGA",
      "Sustitución esferas",
      "Perfil infrarrojo",
    ],
    technicalData: "Soldadura con plomo o SAC305 alta durabilidad.",
  },
  {
    type: "cctv-installation-maintenance",
    typeSpeciality: "security-camera-installation",
    slug: "instalacion-mantenimiento-camaras-seguridad",
    title: "Cámaras de Seguridad",
    icon: Cctv,
    description: "Instalación y monitoreo de videovigilancia HD e IP.",
    longDescription:
      "Configuración de monitoreo remoto y optimización de grabación en DVR/NVR.",
    image: "/assets/images/services/cctv-installation-maintenance.png",
    includes: [
      "Instalación cámaras IP",
      "Monitoreo remoto",
      "Mantenimiento DVR",
    ],
    technicalData: "Acceso seguro mediante P2P/DDNS.",
  },
  {
    type: "intercom-system-installation",
    typeSpeciality: "intercom-installation",
    slug: "instalacion-y-reparacion-de-intercomunicadores",
    title: "Intercomunicadores",
    icon: PhoneCall,
    description: "Instalación de videoporteros y citófonos digitales.",
    longDescription:
      "Instalación de frentes de calle y cerraduras eléctricas con audio claro.",
    image: "/assets/images/services/intercom-system-installation.png",
    includes: ["Frentes de calle", "Videoporteros", "Cerraduras eléctricas"],
    technicalData: "Sistemas digitales de alta fidelidad.",
  },
  {
    type: "mechanical-components-repair",
    typeSpeciality: "printer-and-copier-repair",
    slug: "reparacion-componentes-mecanicos-impresora",
    title: "Rodillos y Fajas",
    icon: Settings2,
    description: "Reparación de sistemas de tracción y ruidos mecánicos.",
    longDescription:
      "Sustitución de Pick-up Rollers y lubricación de engranajes internos.",
    image: "/assets/images/services/printer-and-copier-repair.png",
    includes: ["Gomas de arrastre", "Fajas transferencia", "Lubricación"],
    technicalData: "Lubricantes de alta temperatura.",
  },
  {
    type: "laser-unit-repair",
    typeSpeciality: "printer-and-copier-repair",
    slug: "reparacion-unidad-laser-copiadora",
    title: "Unidad Láser / Escáner",
    icon: ScanLine,
    description: "Diagnóstico de impresiones borrosas o errores ópticos.",
    longDescription:
      "Limpieza de espejos poligonales y calibración de unidad de exposición.",
    image: "/assets/images/services/printer-and-copier-repair.png",
    includes: ["Limpieza espejos", "Calibración láser", "Motores poligonales"],
    technicalData: "Ajuste de densidad DPI nativa.",
  },
  {
    type: "logic-board-printer-repair",
    typeSpeciality: "printer-and-copier-repair",
    slug: "reparacion-placa-logica-impresora",
    title: "Placa Lógica Impresora",
    icon: CircuitBoard,
    description: "Reparación de circuitos y puertos USB/Red.",
    longDescription:
      "Diagnóstico de componentes por sobretensión y actualización de firmware.",
    image: "/assets/images/services/printer-and-copier-repair.png",
    includes: ["Reparación USB/Red", "Diagnóstico SMD", "Update Firmware"],
    technicalData: "Reparación electrónica Nivel Componente.",
  },
  {
    type: "continuous-ink-installation",
    typeSpeciality: "printer-and-copier-repair",
    slug: "instalacion-sistema-tinta-continua",
    title: "Sistema Continuo",
    icon: Droplet,
    description: "Adaptación de sistemas de tinta de alto rendimiento.",
    longDescription:
      "Instalación de tanques externos y dampers para evitar retroceso de tinta.",
    image: "/assets/images/services/printer-and-copier-repair.png",
    includes: ["Montaje tanques", "Purga por vacío", "Instalación dampers"],
    technicalData: "Uso de tintas de alta pigmentación.",
  },
];
